# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: 
      - main
      - feature/*

  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    # - name: Setup MSBuild Path
    #   uses: warrenbuckley/Setup-MSBuild@v1

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: List contents of the current directory
      run: ls

    # - name: Navigate to project directory
    #   run: | 
    #       ls 
    #   working-directory: sequence-insights

    - name: Restore dependencies
      run: dotnet restore
      working-directory: sequence-insights

    - name: Build
      run: dotnet build --no-restore
      working-directory: sequence-insights

    # - name: Log contents of the test directory
    #   run: ls -R sequence-insights/test/SequenceInsights.Tests/bin

    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: sequence-insights

    - name: Run tests with coverage
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      working-directory: sequence-insights

    - name: Add tool directory to PATH
      run: echo "::add-path::$(pwd)/.dotnet/tools"

      
    - name: Generate coverage report
      run: |
         # dotnet tool install -g dotnet-reportgenerator-globaltool
         dotnet tool install --tool-path . dotnet-reportgenerator-globaltool --add-source https://api.nuget.org/v3/index.json --ignore-failed-sources
         ls
         reportgenerator -reports:**/coverage.opencover.xml -targetdir:coverlet-report -reporttypes:Html
         # reportgenerator -reports:/agent/_work/1/s/UnitTestResults/coverage.cobertura.xml -targetdir:/agent/_work/1/s/UnitTestResults/cobertura -reporttypes:HtmlInline_AzurePipelines
      # working-directory: sequence-insights

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverlet-report
        path: coverlet-report
